// Chandler Wixom 3/26/2025 Lab 8 Project Euler
//1,2,4,5,6


// intro
using System.Runtime.InteropServices;
do
{
Console.Clear();
int problem = ReadNumber(5, 1);
Console.Clear();

switch (problem)
{
    case 1:
        Multiples();

        break;
    
    case 2:
        EvenFibonacci();

        break;

    case 3:
        PalindromeProduct();

        break;

    case 4:
        SmallestMultiple();

        break;

    case 5:
        SquareDifference();

        break;
    
}
Console.ReadKey(true);
} while (true);




//1
static void Multiples()
{
    Console.WriteLine("Find the sum of all the multiples of 3 and 5 below 1000.\n");

    //of 3
    int sumOf3 = 0;
    Console.WriteLine("The multiples of 3 are:");
    for (int i = 1; i * 3 < 1000; i++)
    {
        Console.Write(i * 3 + " ");
        sumOf3 = sumOf3 + i * 3;
    }
    Console.WriteLine($"\nand there sum is {sumOf3}\n");


     //of 5
    int sumOf5 = 0;
    Console.WriteLine("The multiples of 5 are:");
    for (int i = 1; i * 5 < 1000; i++)
    {
        Console.Write(i * 5 + " ");
        sumOf5 = sumOf5 + i * 5;
    }
    Console.WriteLine($"\nand there sum is {sumOf5}");
}


// 2
static void EvenFibonacci()
{
    Console.WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms.\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.");
    long sum = 2;
    long temp = 0;
    long last = 1;
    long recent = 2;
    //starting numbers
    Console.Write("These numbers are\n0 2 ");

    while (recent < 4_000_000)
    {
        temp = last + recent;
        last = recent;
        recent = temp;
        if (temp < 4_000_000)
        {
            if (temp % 2 == 0)
            {
                sum = sum + temp;
              Console.Write(temp + " ");
            }
        }

    }
    Console.WriteLine($"\nThe sum of these is {sum}");


}


//3
static void PalindromeProduct()
{

}


//4
static void SmallestMultiple()
{

}


//5
static void SquareDifference()
{

}




// Writes the into stuff
void WriteIntro()
{
Console.WriteLine("This is a program that will demonstrate the solution to five Project Euler problems");
Console.Write("1. Multiples of 3 or 5\n2. Even Fibonacci Numbers\n3. Largest Palindrome Product\n4. Smallest Multiple\n5. Sum Square Difference\nPlease select a problem to be demonstrated: ");
}

// reads int between the max and min if fail rewrites intro and tries again
 int ReadNumber(int max, int min)
{
    do
    {
        
    WriteIntro();
   bool pass = Int32.TryParse(Console.ReadLine() , out int number);

    if (!pass)
    {
        Console.Clear();
        Console.SetCursorPosition(50,6);
    Console.WriteLine("Hmm?");
    Console.SetCursorPosition(0,0);
    }
   else if (number < min || number > max)
   {
    Console.Clear();
    Console.SetCursorPosition(50,6);
    Console.WriteLine("Sorry Out of Range");
    Console.SetCursorPosition(0,0);
   }
   else 
   {
    return number;
   }


    } while (true);
}